import ReduxProvider from '@/redux/ReduxProvider';
import '../globals.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import DashboardNavbar from '@/containers/dashboardNavbar/DashboardNavbar';

import 'swiper/scss';
import 'swiper/scss/effect-fade';
import 'swiper/scss/navigation';
import 'swiper/scss/pagination';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <ReduxProvider>
        <body className="dashboard_body">
          <nav>
            <DashboardNavbar />
          </nav>

          <main className="dashboard_main">{children}</main>
        </body>
      </ReduxProvider>
    </html>
  );
}
